
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Brobeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-brobeat>>
* <<exported-fields-cloud>>
* <<exported-fields-http>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-brobeat]]
== brobeat Fields

Brobeat - Monitors Bro NSM logs and sends them to Elasticsearch



[float]
=== test

TEST


[[exported-fields-cloud]]
== Cloud Provider Metadata Fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== meta.cloud.provider

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== meta.cloud.instance_id

Instance ID of the host machine.


[float]
=== meta.cloud.machine_type

example: t2.medium

Machine type of the host machine.


[float]
=== meta.cloud.availability_zone

example: us-east-1c

Availability zone in which this host is running.


[float]
=== meta.cloud.project_id

example: project-x

Name of the project in Google Cloud.


[float]
=== meta.cloud.region

Region in which this host is running.


[[exported-fields-http]]
== HTTP Fields

HTTP requests and replies



[float]
=== created

type: date

format: yyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis

required: True

Date the log file was created


[float]
=== ts

type: double

Timestamp for when the request happened.


[float]
=== uid

type: text

Unique ID for the connection.


[float]
=== id.orig_h

type: ip

The originator's IP address.


[float]
=== id.orig_p

type: integer

The originator's port number.


[float]
=== id.resp_h

type: ip

The responder's IP address.


[float]
=== id.resp_p

type: integer

The responder's port number.


